create table sources (
  id bigint generated by default as identity primary key,
  name text not null,
  base_url text not null,
  type text not null check (type in ('rss', 'html', 'json_api')),
  enabled boolean default true,
  parser_config jsonb default '{}'::jsonb,
  last_scraped_at timestamptz
);

create table events (
  id bigint generated by default as identity primary key,
  canonical_title text not null,
  peril text not null,
  location_text text,
  lat double precision,
  lng double precision,
  severity_score int default 0,
  first_seen_at timestamptz default now(),
  last_updated_at timestamptz default now(),
  event_key text unique not null
);

create table articles (
  id bigint generated by default as identity primary key,
  source_id bigint references sources(id),
  event_id bigint references events(id),
  external_url text unique not null,
  title text not null,
  summary text,
  published_at timestamptz not null,
  fetched_at timestamptz default now(),
  raw_data jsonb,
  author text
);

create index idx_events_last_updated on events(last_updated_at desc);
create index idx_articles_url on articles(external_url);
create index idx_articles_event on articles(event_id);

insert into sources (name, base_url, type, parser_config) values
('USGS Earthquakes', '[https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson](https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson)', 'json_api', '{"format": "usgs"}'),
('Reinsurance News', '[https://www.reinsurancene.ws/feed/](https://www.reinsurancene.ws/feed/)', 'rss', '{}'),
('Artemis', '[https://www.artemis.bm/feed/](https://www.artemis.bm/feed/)', 'rss', '{}'),
('Insurance Journal', '[https://www.insurancejournal.com/rss/news/international/](https://www.insurancejournal.com/rss/news/international/)', 'rss', '{}'),
('Haggie Partners', '[https://www.haggiepartners.com/press-releases/](https://www.haggiepartners.com/press-releases/)', 'html', '{"selector": ".post"}');
